---
- name: Change timezone
  ansible.builtin.include_tasks:
    file: set-timezone.yml

- name: Install caddy
  ansible.builtin.include_tasks:
    file: install-caddy.yml

- name: Install docker
  ansible.builtin.include_tasks:
    file: install-docker.yml

- name: Install restic
  ansible.builtin.include_tasks:
    file: install-restic.yml
