---
- name: Prepare for installation of containerd for ol8
  block:
    - name: Remove podman
      ansible.builtin.package:
        name: podman
        state: absent

    - name: Introduce Docker's offical repo
      ansible.builtin.yum_repository:
        name: docker-ce
        description: docker-ce repo, added by Ansible
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable

  when: ansible_facts['os_family'] == "RedHat"

- name: Install containerd
  ansible.builtin.package:
    name: containerd
    state: present
    update_cache: true

- name: Ensure containerd is running and enabled.
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true

- name: Ensure containerd config directory exists.
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"
  # register: containerd_dir

# - name: Get stats of containerd config file
# ansible.builtin.stat:
#  path: /etc/containerd/config.toml
# register: containerd_config_file
- name: Generete default config from containerd.
  ansible.builtin.command: containerd config default
  changed_when: false
  register: containerd_config_default
  when: containerd_running_config_overwrite
  # when: containerd_config_file.islnk is undefined or not containerd_config_file.islnk or containerd_config_default.pw_name != "root"

- name: Prepare containerd's config file from default
  ansible.builtin.copy:
    dest: /tmp/containerd_config.toml
    content: "{{ containerd_config_default.stdout }}"
    owner: root
    group: root
    mode: "0644"
  changed_when: false
  # when: containerd_config_file.islnk is undefined or not containerd_config_file.islnk or containerd_config_default.pw_name != "root"

- name: Set Cgroup driver to systemd
  ansible.builtin.lineinfile:
    insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
    line: "          SystemdCgroup = true"
    state: present
    path: /tmp/containerd_config.toml
  changed_when: false

- name: Make sure there is no "SystemdCgroup = false"
  ansible.builtin.lineinfile:
    path: /tmp/containerd_config.toml
    state: absent
    line: "            SystemdCgroup = false"
  notify: restart containerd
  changed_when: false

- name: Copy config.toml to /etc/containerd
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/containerd_config.toml
    dest: /etc/containerd/config.toml
    backup: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart containerd
  when: containerd_running_config_overwrite
  # when: containerd_config_file.islnk is undefined or not containerd_config_file.islnk or containerd_config_default.pw_name != "root"

- name: Cleanup temporary file
  ansible.builtin.file:
    path: /tmp/containerd_config.toml
    state: absent
  changed_when: false

- name: Ensure containerd is restarted immediately if necessary.
  ansible.builtin.meta: flush_handlers
