---
- name: Remove swap mount
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Unconditionally reboot the machine
  ansible.builtin.reboot:
  when: ansible_swaptotal_mb > 0
